layout_spectrum: 0.006241393741220236
typography_spectrum: 0.6655611617024988
color:
  brandStrength: 0.009951303014531732
  lightness: 0.5587293535936624
  saturation: 0.6489797041285783
  rhythmicContrast: 0.1108989140484482
  brandColors:
    - '#2F2933'
    - '#01A2A6'
    - '#29D9C2'
    - '#BDF271'
    - '#FFFFA6'
name: Art Board Co
navigation:
  - url: 'http://www.instagram.com/artboardco'
    name: Let's Connect on Instagram
    type: external
  - url: 'http://www.facebook.com/artboardco'
    name: Let's Chat on Facebook
    type: external
  - url: 'http://www.twitter.com/artboardco'
    name: Tweet Us!
    type: external
