title: Art Board Co
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6489797041285783
  brandStrength: 0.009951303014531732
  rhythmicContrast: 0.1108989140484482
  brandColors:
    - '#2F2933'
    - '#01A2A6'
    - '#29D9C2'
    - '#BDF271'
    - '#FFFFA6'
  lightness: 0.5587293535936624
typography_spectrum: 0.6035448
navigation:
  - url: 'http://www.instagram.com/artboardco'
    name: Let's Connect on Instagram
    type: external
  - url: 'http://www.facebook.com/artboardco'
    name: Let's Chat on Facebook
    type: external
layout_spectrum: 0.05783582
name: Art Board Co
